function [param, idx_out]=ajr_train(X_train, Y_train, idx_in)
	X=X_train(:,idx_in);
	Posidx=find(Y_train>0);
	Negidx=find(Y_train<0);
	Mu1=mean(X(Posidx,:));
	Mu2=mean(X(Negidx,:));
	Sigma1=std(X(Posidx,:),1);
	Sigma2=std(X(Negidx,:),1);
	param.W=(Mu1-Mu2)./(Sigma1+Sigma2);
	B=(Mu1+Mu2)/2;
	param.b=-param.W*B';
	idx_out=idx_in;
